apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-hpa
spec:
  selector:
    matchLabels:
      app: go-hpa
  template:
    metadata:
      labels:
        app: go-hpa
    spec:
      containers:
      - name: go-hpa
        image: felipebergamin/go-hpa
        resources:
          requests:
            memory: "256Mi"
            cpu: "50m"
          limits:
            memory: "400Mi"
            cpu: "100m"
        ports:
        - containerPort: 8000
